name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    env:
      npm_execpath: pnpm
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7.1.7
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '17.7.1'
      - name: Build
        run: |
          pnpm i
          pnpm docs:build
      - name: Push to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          force_orphan: true
